namespace Compiler.Common
{
    public enum TokenType
    {
        Identifier,
        Integer,
        ParenthesisOpen,
        ParenthesisClose,
        Nothing,
        EndOfFile,
        Division,
        Multiplication,
        EmptyString,
        EndMarker,
        Boolean,
        String,
        Or,
        And,
        RelOp,
        Hash,
        Comma,
        Select,
        From,
        Where,
        Join,
        On,
        Insert,
        Into,
        Values,
        Top
    }
}
